INSERT INTO PERSON (ID, NAME, AGE) VALUES (1, 'Dominik', 55);
INSERT INTO PERSON (ID, NAME, AGE) VALUES (2, 'Juerg',   44);
INSERT INTO PERSON (ID, NAME, AGE) VALUES (3, 'Peter',   33);
INSERT INTO PERSON (ID, NAME, AGE) VALUES (4, 'Daniel',  33);

