INSERT INTO ADDRESS (ID, STREET, CITY) VALUES (1, 'Bahnhofstrasse 6', 'Windisch');

INSERT INTO ORDERS  (ID) VALUES (1);

INSERT INTO CUSTOMER (ID, AGE, NAME, ADDRESS_ID) VALUES(1, 22, 'Mueller', 1);
INSERT INTO CUSTOMER (ID, AGE, NAME) VALUES(2, 23, 'Schneider');

